# Generated by Django 3.1.2 on 2022-07-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20220709_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='scopes',
            new_name='category',
        ),
    ]
