# Generated by Django 3.1.2 on 2022-07-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20220709_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['-is_main'], 'verbose_name': 'Связь', 'verbose_name_plural': 'Связи'},
        ),
    ]
