# Generated by Django 4.0.6 on 2022-07-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_group_alter_student_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.ManyToManyField(max_length=30, related_name='students', to='school.teacher', verbose_name='Имя'),
        ),
    ]
